spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/codeache?currentSchema=lifeplanner}
    username: ${DB_USER:postgres_user}
    password: ${DB_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver