openapi: 3.0.0
info:
  title: LifePlanner Service - OpenAPI 1.0
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/customer
tags:
  - name: LifePlanner
    description: LifePlanner API
paths:
  /v1/problem:
    post:
      operationId: createProblem
      summary: Create new problem
      tags:
        - LifePlanner
      requestBody:
        description: Problem create request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProblemDto'
        required: true
      responses:
        '201':
          description: Problem was created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssueId'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '401':
          description: Not authorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '405':
          description: Method is not available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

components:
  schemas:
    ErrorResponseDto:
      type: object
      properties:
        message:
          type: string
          description: Error message
        code:
          type: integer
          description: Error status code
        traceId:
          type: string
          description: Trace Id

    CreateProblemDto:
      type: object
      properties:
        problemName:
          type: string
          maxLength: 256
          nullable: false
          description: Problem name

    IssueId:
      type: string


security:
  - bearerAuth: [ ]